# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/data-preprocessing/" 
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "pip"
    directory: "/lambda/" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/pipeline/" 
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directory: "/iac/" 
    schedule:
      interval: "weekly"
