apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ .Values.secrets.awsDefaultRegion | b64enc | quote }}
  SAGEMAKER_ENDPOINT_NAME: {{ .Values.secrets.sagemakerEndpointName | b64enc | quote }}