apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-helm-chart.fullname" . }}
  labels:
    {{- include "frontend-helm-chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "stremlit-port"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "frontend-helm-chart.name" . }}