apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "<your-base64-access-key-id>"
  AWS_SECRET_ACCESS_KEY: "<your-base64-access-key>"
  AWS_DEFAULT_REGION: "<your-base64-region>"
  SAGEMAKER_ENDPOINT_NAME: "<your-base64-sagemaker-endpoint-name>"
