name: Build and Deploy Frontend Docker Image

on:
    workflow_dispatch:
    push:
        paths:
            - 'frontend/**'
        branches:
            - main

permissions:
  contents: read
  packages: write

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                install: true

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: ./frontend/src/
                push: true
                platforms: linux/amd64,linux/arm64
                tags: |
                  ghcr.io/${{ github.repository_owner }}/mlops-frontend:${{ github.sha }}